### ISSUE TITLE
Trying to get specs passing on my machine

### ISSUE THREAD

**Issue by coreyhaines** [wbez/curiouscity#4]
So, this isn't really an issue with the repo (I hope) as much as my configuration. I figure maybe @darrencauthon might be kind enough to help me figure what I'm missing, since it seems he might have them running on his machine.

So, I got what I think is the right configuration:
Ruby 2.0.0p598
Rails 4.0.0

although I did move to sqlite3 instead of MySql.

I also locked it at rspec-rails 2.14.2 to minimize the deprecation warnings with 2.99, since it is really a version to use when upgrading to 3.0.

Starting with model specs, I get 3 failures:

```
  1) VotingRound#next gets voting round that is completed and previous
     Failure/Error: result.should eq newer_voting_round
       
       expected: #<VotingRound id: 2, start_time: "2014-01-01 03:04:11", end_time: "2014-01-01 03:04:11", created_at: "2015-01-03 23:15:44", updated_at: "2015-01-03 23:15:44", public_label: "Voting Round 2", status: "Live", private_label: "Voting Round 2">
            got: #<VotingRound id: 1, start_time: "2013-10-03 11:03:52", end_time: "2013-10-03 11:03:52", created_at: "2015-01-03 23:15:44", updated_at: "2015-01-03 23:15:44", public_label: "Voting Round 1", status: "Completed", private_label: "Voting Round 1">
       
       (compared using ==)
       
       Diff:
       @@ -1,2 +1,2 @@
       -#<VotingRound id: 2, start_time: "2014-01-01 03:04:11", end_time: "2014-01-01 03:04:11", created_at: "2015-01-03 23:15:44", updated_at: "2015-01-03 23:15:44", public_label: "Voting Round 2", status: "Live", private_label: "Voting Round 2">
       +#<VotingRound id: 1, start_time: "2013-10-03 11:03:52", end_time: "2013-10-03 11:03:52", created_at: "2015-01-03 23:15:44", updated_at: "2015-01-03 23:15:44", public_label: "Voting Round 1", status: "Completed", private_label: "Voting Round 1">
       
     # ./spec/models/voting_round_spec.rb:118:in `block (3 levels) in <top (required)>'

  2) FlickrPicture sets the attributes
     Failure/Error: @photo = double(Flickr::Photo,
     NameError:
       uninitialized constant Flickr::Photo
     # ./spec/models/flickr_picture_spec.rb:15:in `block (2 levels) in <top (required)>'

  3) FlickrPicture url sets the right url from multiple fields
     Failure/Error: @photo = double(Flickr::Photo,
     NameError:
       uninitialized constant Flickr::Photo
     # ./spec/models/flickr_picture_spec.rb:15:in `block (2 levels) in <top (required)>'
```

Darren, did you have to do anything special to get the tests passing? I'm wondering if the Flickr::Photo failures are because there was a commit in July to move to flickr-objects gem.

**Comment by coreyhaines** [comment]
Well, found my first sqlite3 issue. That failure in the voting round is due to this line that has date calculations:

https://github.com/wbez/curiouscity/blob/master/app/models/voting_round.rb#L38-L40

```
  def next
    VotingRound.where('(status = "Live" or status = "Completed") and start_time > "' + self.start_time.to_s + '"').order(start_time: :asc).first
  end
```

I bet in mysql, that date comparison works. If I switch it to (self.start_time + 1.day), then it works.

Looks like perhaps there is more mysql-dependent code than just the Gemfile and that migration. :)

**Comment by coreyhaines** [comment]
Changing to a parameterized query makes it pass in sqlite. Hurray for using ActiveRecord instead of raw sql.

```
  def next
    VotingRound.where('(status = "Live" or status = "Completed") and start_time > ?', self.start_time).order(start_time: :asc).first
  end
```

**Comment by coreyhaines** [comment]
Okay, as I thought, the latest version of the flickr-objects gem uses Flickr::Object::Photo. Changing to this in the spec made it pass.

@darrencauthon did you see this?

**Comment by coreyhaines** [comment]
Closing, as I'm moving to a fork of it under my account.

**Comment by darrencauthon** [comment]
@coreyhaines I didn't use the project much last year.  Another station was considering hosting a version of this application themselves, so as a favor I looked at it first to see if it would be feasible.  

I made the change I did to get the application working.  I made sure I could get the website to come up on my computer, that the logins worked, and the basic operations were operational.  I was able to create records and vote on them.  I think I was using sqlite3, but I might have been using postgres.  

At that point, I passed it to @davidames1983 to see if he could get it running on Heroku.  And he did!  Pinging him on this in case he has any comments on this application.

As for running the tests... I didn't get that far.  This work was a favor, and I wanted to limit the (free) time we invested in it until we got a firm commitment that the station would want it.  Which was a good call, as somebody there changed their mind.  But I thought it was a neat app and I've always been curious to see how it could be reskinned and reused.  I'll watch your fork. :smile:

**Comment by coreyhaines** [comment]
@darrencauthon ah, thanks for the background. I can totally understand about time commitment on a favor.

What station were you talking to? I recently discovered the podcast, and I like it a lot.

**Comment by darrencauthon** [comment]
Podcast?  There's a podcast? :smile:

The station was KCPT, the local PBS affiliate.

**Comment by coreyhaines** [comment]
WBEZ does one for Chicago. http://curiouscity.wbez.org/
You can search for curious city in a podcast app, and you should find it. Super interesting stuff.
